
export const practices=[
["criminal-law","Criminal Law","Strategic representation and advisory support in criminal complaints, investigations, bail matters and proceedings."],
["civil-litigation","Civil Litigation","Focused dispute strategy for civil claims, injunctions, recovery proceedings and contested matters."],
["commercial-law","Commercial Law","Practical legal guidance for businesses, entrepreneurs, transactions and commercial relationships."],
["corporate-advisory","Corporate Advisory","Day-to-day legal support on governance, risk, compliance and commercial decision-making."],
["arbitration-adr","Arbitration & ADR","Representation and advice in arbitration, mediation, negotiation and other private dispute-resolution processes."],
["intellectual-property","Intellectual Property","Advice on trademarks, copyright, licensing, confidential information and IP-related disputes."],
["data-protection","Data Protection & Privacy Law","Advisory support on privacy, cybersecurity, data governance, compliance and technology-related legal risk."],
["family-law","Family Law","Sensitive and practical advice in matrimonial, domestic and related family matters."],
["property-law","Property Law","Advice and representation in ownership, possession, tenancy, development and property disputes."],
["consumer-law","Consumer Law","Representation in consumer complaints involving goods, services and unfair practices."],
["contract-drafting","Contract Drafting","Clear, commercially focused drafting and review of agreements with careful attention to risk allocation."]
];
export const lawyers=[
{name:"Dr. Adv. Bhooshan B. Agalgatti",role:"Senior Partner",photo:"/bhooshan.jpeg",quals:"BSc, LLB, MBA, DLL&LW, DCPL, DPMIR, DBM, ISTD Dip (T&D), DOA, PGDHRM, PGDT&D, PhD",focus:["Criminal Law","Civil Litigation","Commercial Litigation","Corporate Advisory"],bio:"Dr. Adv. Bhooshan B. Agalgatti brings together legal, commercial, labour-law and management expertise. His multidisciplinary background supports a pragmatic approach to complex disputes, advisory assignments and client strategy. He works closely with individuals and businesses to identify the legal issues that matter most, assess risk realistically and pursue solutions with clarity, preparation and professional judgment."},
{name:"Dr. Adv. Bhoomika Agalgatti",role:"Senior Partner",photo:"/bhoomika.jpeg",quals:"BA, MBA, BEd, LLB, ISTD Dip (T&D), PhD",focus:["Family Law","Property Law","Civil Law"],bio:"Dr. Adv. Bhoomika Agalgatti combines legal knowledge with extensive academic, management and training experience. Her approach is careful, structured and client-focused, particularly in matters requiring sensitivity, communication and practical problem-solving. She advises clients on civil, family and property-related issues with an emphasis on clarity, discretion and workable legal outcomes."},
{name:"Adv. Ruben Ashwin Rao",role:"Partner",photo:"/ruben.jpeg",quals:"LLM in Data Protection and Cybersecurity (UCD, Dublin), LLB, Certificate in CrPC and Arbitration",focus:["Data Protection","Cyber Law","Arbitration","Commercial Law"],bio:"Adv. Ruben Ashwin Rao focuses on data protection, cybersecurity, commercial matters and dispute resolution. His postgraduate training in Dublin gives him an international perspective on privacy, technology governance and emerging regulatory risk. He assists clients in understanding legal obligations, structuring practical compliance approaches and addressing disputes involving commercial and technology-related issues."},
{name:"Adv. Sahil Sanjay Jagtap",role:"Partner",photo:"/sahil.jpg",quals:"LLM in International Arbitration (QMUL, London), BBA LLB, Certificate in CrPC and Arbitration",focus:["Arbitration","Intellectual Property","Commercial Law","Contract Drafting"],bio:"Adv. Sahil Sanjay Jagtap works across arbitration, intellectual property, commercial law and contract drafting. His international arbitration training in London informs a strategic approach to disputes, negotiation and cross-border legal issues. He assists individuals and businesses with clear legal analysis, carefully structured agreements and practical dispute-resolution strategies."},
{name: "Adv. Novella Martis",role: "Associate",photo: "/novella-martis.jpeg",quals: "BCom, LLB, PG Diploma in IPR Law",focus: ["Family Law","Corporate & Commercial Law","Intellectual Property"],bio: "Adv. Novella Martis is dedicated to providing clear, practical and effective legal solutions. With a strong foundation in family law, corporate and commercial law, and intellectual property, she provides end-to-end legal consultation, strategic drafting and litigation support tailored to the personal and business requirements of her clients."},
{name: "Adv. Sukeshani Abhiman Thombare",role: "Associate",photo: "/sukeshani-thombare.jpeg",quals: "BA, LLB, Certificate Course in CrPC",focus: ["Criminal Law","Co-operative Society Law","Family Law","Civil Litigation"],bio: "Adv. Sukeshani Abhiman Thombare focuses on criminal law, co-operative society laws and family law. She represents clients in criminal proceedings, co-operative court disputes, matrimonial matters, divorce, maintenance, child custody and domestic violence cases. She also advises clients on civil and property-related matters, combining thorough legal research with a practical, client-focused approach to deliver effective legal solutions."}
];
