
import Link from "next/link";
import Reveal from "@/components/Reveal";
import {practices,lawyers} from "./data";
export default function Home(){
return <main>
<section className="hero"><div className="container heroContent"><div className="eyebrow">Multidisciplinary Legal Practice</div><div className="goldLine"/><h1>Strategic Legal Solutions<br/><span style={{color:"var(--gold-light)"}}>Across Borders.</span></h1><p>Providing trusted legal counsel in India and internationally across dispute resolution, commercial matters, intellectual property, arbitration, data protection, and litigation.</p><div className="heroActions"><Link className="btn" href="/contact">Book Consultation</Link><Link className="btn outline" href="/practice-areas">Explore Practice Areas</Link></div></div></section>
<section className="section white"><div className="container split"><Reveal><div className="eyebrow">A Modern Legal Practice</div><h2>Client-first. Technology-driven. International in outlook.</h2><p>LARS Legal Associates is a multidisciplinary legal practice established to deliver clear, strategic and solution-oriented legal services to individuals and businesses.</p><p>We combine careful legal analysis, practical commercial judgment and responsive client service across litigation, advisory work and dispute resolution.</p><Link className="btn dark" href="/about">About the Firm</Link><div className="stats"><div className="stat"><b>11</b><br/>Practice areas</div><div className="stat"><b>4</b><br/>Global locations</div><div className="stat"><b>4</b><br/>Lawyers</div><div className="stat"><b>Client-First</b><br/>Approach</div></div></Reveal><Reveal><div className="photoFrame"><img src="/office-chamber.jpeg" alt="LARS Legal Associates chamber"/></div></Reveal></div></section>
<section className="section dark"><div className="container"><div className="eyebrow">Practice Areas</div><h2>Integrated legal support.</h2><div className="grid">{practices.slice(0,6).map((p,i)=><Reveal key={p[0]} delay={i*.04}><div className="card"><span className="num">{String(i+1).padStart(2,"0")}</span><h3><Link href={`/practice-areas/${p[0]}`}>{p[1]}</Link></h3><p>{p[2]}</p></div></Reveal>)}</div><p style={{marginTop:"2rem"}}><Link className="btn" href="/practice-areas">View All Practice Areas</Link></p></div></section>
<section className="section"><div className="container"><div className="eyebrow">Why LARS</div><h2>Built around the client.</h2><div className="why"><Reveal><div><h3>Client-First</h3><p>Clear communication, practical advice and strategies shaped around the client’s actual objectives.</p></div></Reveal><Reveal delay={.1}><div><h3>Modern Practice</h3><p>A multidisciplinary approach combining law, business, technology and dispute resolution.</p></div></Reveal><Reveal delay={.2}><div><h3>Technology-Driven</h3><p>Efficient communication and a strong focus on emerging regulatory issues.</p></div></Reveal></div></div></section>
<section className="section white"><div className="container"><div className="eyebrow">Our Lawyers</div><h2>A multidisciplinary team.</h2><div className="teamGrid">{lawyers.map((m,i)=><Reveal key={m.name} delay={i*.05}><div className="member"><img src={m.photo} alt={m.name}/><div className="memberBody"><small>{m.role}</small><h3>{m.name}</h3><div className="tags">{m.focus.slice(0,2).map(x=><span className="tag" key={x}>{x}</span>)}</div></div></div></Reveal>)}</div><p style={{marginTop:"2rem"}}><Link className="btn dark" href="/team">Meet the Team</Link></p></div></section>
<section className="section dark"><div className="container split"><Reveal><div className="eyebrow">Global Presence</div><h2>Connected across four jurisdictions.</h2><p>Our offices and contact locations support clients in India, the United Kingdom, Ireland and the United States, subject to applicable local laws and professional requirements.</p><Link className="btn" href="/locations">Explore Locations</Link></Reveal><Reveal><div className="world"><div className="pin india"><span>India</span></div><div className="pin uk"><span>United Kingdom</span></div><div className="pin ireland"><span>Ireland</span></div><div className="pin usa"><span>United States</span></div></div></Reveal></div></section>
<section className="section"><div className="container"><div className="eyebrow">Pune Office</div><h2>Designed for focused, confidential counsel.</h2><Reveal><div className="gallery"><img src="/office-entry.jpeg" alt="Office reception"/><img src="/office-workspace.jpeg" alt="Office workspace"/><img src="/office-corridor.jpeg" alt="Office corridor"/><img src="/office-chamber.jpeg" alt="Meeting room"/></div></Reveal></div></section>
</main>}
